apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-healthcheck-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-healthcheck-simulator
  template:
    metadata:
      labels:
        app: k8s-healthcheck-simulator
    spec:
      containers:
        - name: k8s-healthcheck-simulator-container
          image: thilinaba/k8s-healthcheck-simulator:0.0.1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: STARTUP_STATE
              value: "true" # "true" - startup probe returns success | "false" - startup probe returns failure
            - name: READY_STATE
              value: "true" # "true" - readiness probe returns success | "false" - readiness probe returns failure
            - name: LIVE_STATE
              value: "true" # "true" - liveness probe returns success | "false" - liveness probe returns failure
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/startup
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-healthcheck-simulator-service
spec:
  selector:
    app: k8s-healthcheck-simulator
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP